# Generated by Django 5.2.1 on 2025-05-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_initial_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
    ]
