# Generated by Django 5.2.1 on 2025-06-05 10:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_driver_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Класс')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Класс животных',
                'verbose_name_plural': 'Классы животных',
            },
        ),
        migrations.CreateModel(
            name='Enclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Площадь (кв.м)')),
                ('has_water', models.BooleanField(default=False, verbose_name='Есть водоем')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
            },
        ),
        migrations.CreateModel(
            name='FeedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Вид корма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид корма',
                'verbose_name_plural': 'Виды корма',
            },
        ),
        migrations.CreateModel(
            name='HabitatCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна обитания',
                'verbose_name_plural': 'Страны обитания',
            },
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='cargo_types',
        ),
        migrations.RemoveField(
            model_name='service',
            name='cargo_types',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cargo_type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='services',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='services',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='body_type',
        ),
        migrations.CreateModel(
            name='AnimalFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Семейство')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('animal_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.animalclass', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Семейство животных',
                'verbose_name_plural': 'Семейства животных',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('species', models.CharField(max_length=100, verbose_name='Вид')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animals/', verbose_name='Фото')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('arrival_date', models.DateField(verbose_name='Дата поступления в зоопарк')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='В зоопарке')),
                ('animal_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.animalclass', verbose_name='Класс')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.animalfamily', verbose_name='Семейство')),
                ('enclosure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.enclosure', verbose_name='Помещение')),
                ('feed_types', models.ManyToManyField(to='core.feedtype', verbose_name='Виды корма')),
                ('habitat_countries', models.ManyToManyField(to='core.habitatcountry', verbose_name='Страны обитания')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('assigned_animals', models.ManyToManyField(blank=True, related_name='caretakers', to='core.animal', verbose_name='Закрепленные животные')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('assigned_enclosures', models.ManyToManyField(blank=True, related_name='employees', to='core.enclosure', verbose_name='Закрепленные помещения')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Количество (кг)')),
                ('feeding_time', models.TimeField(verbose_name='Время кормления')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата кормления')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.animal', verbose_name='Животное')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee', verbose_name='Сотрудник')),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.feedtype', verbose_name='Вид корма')),
            ],
            options={
                'verbose_name': 'Кормление',
                'verbose_name_plural': 'Кормления',
                'ordering': ['-date', 'feeding_time'],
            },
        ),
        migrations.DeleteModel(
            name='CargoType',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='VehicleBodyType',
        ),
    ]
