# Generated by Django 5.2.1 on 2025-05-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_news_updated_at_alter_news_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/', verbose_name='Фотография'),
        ),
    ]
