version: "3.8"

networks:
  my_network:
    driver: bridge

services:
  apache:
    image: php:7.4-apache
    container_name: apache_server
    ports:
      - "8080:80"
    volumes:
      - ./your_project:/var/www/html
      - ./config.php:/var/www/html/config.php
    networks:
      - my_network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_ui
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - my_network

volumes:
  db_data:
