@echo off
echo Настройка проекта для ЛР 1 HTML...

echo Активация виртуального окружения...
call venv\Scripts\activate.bat

echo Создание миграций...
python manage.py makemigrations

echo Применение миграций...
python manage.py migrate

echo Создание суперпользователя...
echo Если суперпользователь уже существует, нажмите Ctrl+C для отмены
python manage.py createsuperuser

echo Заполнение базы данных тестовыми данными...
python manage.py populate_lab_data

echo Сбор статических файлов...
python manage.py collectstatic --noinput

echo Запуск сервера разработки...
python manage.py runserver

pause
